version: '3'
services:
  web:
    environment:
      - CHOKIDAR_USEPOLLING=true # esto es para que se detecten los cambios.
    stdin_open: true
    build:
      context: . # especifica donde queremos todos los archivos y carpetas para la imagen que 
      # hacemos pull en este caso se quiere toda la carpeta en donde se encuentra el docker-compose
      dockerfile: Dockerfile.dev # va a ser la localizacion del dockerfile que se va a usar para 
      # construir la imagen
    ports:
      - "3000:3000"
    volumes:
     - /app/node_modules
     - .:/app
  tests:
    environment:
      - CHOKIDAR_USEPOLLING=true # esto es para que se detecten los cambios.
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev 
    volumes:
     - /app/node_modules
     - .:/app
    command: ["npm", "run", "test"]